# Jekyll Digital Collection Generator, GH-Pages version

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
# title of site appears in banner
title: GH-Pages Collection
# tag line appears in banner
tagline: a theme for building simple digital exhibits
# description appears in meta tags and other locations
description: "A more complete description that will appear in meta tags and other locations where appropriate"
# keywords appear in meta tags 
keywords: university of idaho, digital collections, digital humanities
# creator email for meta tags
email: ewilliamson@uidaho.edu

# url variables
# url is your gh-pages base, username.github.io
url: https://uidaholib.github.io
# baseurl is your repository's name prefixed with a /
baseurl: /pages-collection

# repository-name: jekyll-collection

# collection display variables 
# see _data/metadata-fields.csv

permalink: pretty
